stages:
    - compile
    - package
    - deploy
    - purge-cache

generate-html:
    image: klakegg/hugo:alpine
    stage: compile
    script:
        - hugo -D


#   package-docker:
#     image: docker:19
#     stage: package
#     services:
#       - docker:19-dind
#     variables:
#       DOCKER_TLS_CERTDIR: ''
#       DOCKER_HOST: tcp://127.0.0.1:2375
#     only:
#       - master
#     script:
#       - docker build -t registry.gitlab.com/fria/repsy/repsy-landing .
#       - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
#       - docker push registry.gitlab.com/fria/repsy/repsy-landing:latest
  
#   kubernetes-deploy:
#     image: roffe/kubectl
#     stage: deploy
#     only:
#       - master
#     script:
#       - sh deploy-kubernetes.sh
  
#   purge-cloudflare-cache:
#     image: appropriate/curl
#     stage: purge-cache
#     only:
#       - master
#     script:
#       - sh purge-cache.sh
  